# .github/workflows/scheduled-builds.yml
name: Trigger Pause Session

on:
  schedule:
    # Runs "at minute 2 past every hour" (see https://crontab.guru)
    - cron: '* * * * *'
jobs:
  gridai-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gridai-actions/gridai-login@v0
        with:
          gridai-username: ${{ secrets.GRIDAI_USERNAME }} 
          gridai-key: ${{ secrets.GRIDAI_KEY }} `
      - run: |
          grid session pause ${{ secrets.SESSION_NAME }} 
          
           
            
